# This is the configuration used to check the rubocop source code.
require: rubocop-rspec

inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
  TargetRubyVersion: 2.1

Style/Encoding:
  EnforcedStyle: never
  Enabled: true

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

# Style/IndentHeredoc:
#   EnforcedStyle: auto_detection

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

# Lint/AmbiguousBlockAssociation:
#   Exclude:
#     - 'spec/**/*.rb'